

module.exports = function getMovie() {
    return [
      {id:'goonies', name:'The Goonies', synopsis: `Old-fashioned yarn about a band of adventurous kids who take on the might of a property developing company which plans to destroy their home to build a country club. When the children discover an old pirate map in the attic, they follow it into an underground cavern in search of lost treasure but come up against plenty of dangerous obstacles along the way.`},
      {id:'brotherwht', name:'Brother Where are Thou', synopsis:`Ulysses Everett McGill (George Clooney) is having difficulty adjusting to his hard-labor sentence in Mississippi. He scams his way off the chain gang with simple Delmar (Tim Blake Nelson) and maladjusted Pete (John Turturro), then the trio sets out to pursue freedom and the promise of a fortune in buried treasure. With nothing to lose and still in shackles, their hasty run takes them on an incredible journey of awesome experiences and colorful characters.`},
      {id:'warganmes', name:'WarGames', synopsis:`High school student David Lightman (Matthew Broderick) unwittingly hacks into a military supercomputer while searching for new video games. After starting a game of Global Thermonuclear War, Lightman leads the supercomputer to activate the nation's nuclear arsenal in response to his simulated threat as the Soviet Union. Once the clueless hacker comes to his senses, Lightman, with help from his girlfriend (Ally Sheedy), must find a way to alert the authorities to stop the onset of World War III.`},
      {id:'backtothefuture', name:'Back To The Future',synopsis:`In this 1980s sci-fi classic, small-town California teen Marty McFly (Michael J. Fox) is thrown back into the '50s when an experiment by his eccentric scientist friend Doc Brown (Christopher Lloyd) goes awry. Traveling through time in a modified DeLorean car, Marty encounters young versions of his parents (Crispin Glover, Lea Thompson), and must make sure that they fall in love or he'll cease to exist. Even more dauntingly, Marty has to return to his own time and save the life of Doc Brown.`},
      {id:'strangethings', name:'Strange Things', synopsis:`After the mysterious and sudden vanishing of a young boy, the people of a small town begin to uncover secrets of a government lab, portals to another world, and sinister monsters. ... Trying to help find him, the boy's friends discover a strange little girl, who is on the run from "bad men."`},
      {id:'firstman', name:'First Man', synopsis:`On the heels of their six-time Academy Award®-winning smash, La La Land, Oscar®-winning director Damien Chazelle and star Ryan Gosling reteam for Universal Pictures’ First Man, the riveting story of NASA’s mission to land a man on the moon, focusing on Neil Armstrong and the years 1961-1969. A visceral, first-person account, based on the book by James R. Hansen, the movie will explore the sacrifices and the cost—on Armstrong and on the nation—of one of the most dangerous missions in history. Written by Academy Award® winner Josh Singer (Spotlight), the drama is produced by Wyck Godfrey & Marty Bowen (The Twilight Saga, The Fault in Our Stars) through their Temple Hill Entertainment banner, alongside Chazelle and Gosling. Isaac Klausner (The Fault in Our Stars) executive produces. DreamWorks Pictures co-finances the film.`}
    ]
  }